### PR TITLE
Add lru cache over existing caches

### PR DESCRIPTION
**Pull request by mikegleasonjr**
I did it for myself but I guess it could benefit others, especially that it works in front of any existing cache storage.

### CODE REVIEW

**Comment by shurcooL** [comment]
How does this compare to last two entries of https://github.com/gregjones/httpcache#cache-backends?

> - [`github.com/die-net/lrucache`](https://github.com/die-net/lrucache) provides an in-memory cache that will evict least-recently used entries.
> - [`github.com/die-net/lrucache/twotier`](https://github.com/die-net/lrucache/tree/master/twotier) allows caches to be combined, for example to use lrucache above with a persistent disk-cache.

**Comment by mikegleasonjr** [comment]
Well something in the readme would have been great :/ The presence of third
party cache backends in the core is misleading...

**Comment by mikegleasonjr** [comment]
> Well something in the readme would have been great :/ The presence of third
party cache backends in the core is misleading...

Well shit, I am sorry I just saw it 🤕  I was on my phone...

I had a more thorough look at the other option, thank you for reminding me the first rule of programming: _has it been done?_

But the difference is that one is a LRU in front of any other backend. Upon creation you have to give it an existing cache: `func New(c httpcache.Cache, cap int) httpcache.Cache {}`. It's like a decorator. So you can have a LRU with diskcache, s3cache, memcached, memorycache, etc.

But since some of the options out there were not merged into the core, and since I will be open sourcing the project that its part of, I guess I will just send a PR to update the readme to include it.

Sorry for the noise

**Comment by shurcooL** [comment]
> Sorry for the noise

First of all, no problem, and thanks for contributing.

> But the difference is that one is a LRU in front of any other backend. Upon creation you have to give it an existing cache: `func New(c httpcache.Cache, cap int) httpcache.Cache {}`. It's like a decorator. So you can have a LRU with diskcache, s3cache, memcached, memorycache, etc.

Gotcha, that's what I saw too from a brief look-through.

> But since some of the options out there were not merged into the core, and since I will be open sourcing the project that its part of, I guess I will just send a PR to update the readme to include it.

Let me confirm I understand you correctly, do you mean that you'll put up the lru `httpcache.Cache` implementation in another repo, and then send a PR to update this project's README to refer to it?

If so, that sounds great. I think it's better for the individual cache implementations to live outside, since there's no benefit to have them in the exact same repo. Will happily review that PR once you're ready.

Thanks again!

**Pull request closed without merging**
